version: '3.9'

services:
  django_basic:
    restart: always
    build: .
    ports:
      - "8000:8000"
    links:
      - postgres
    volumes:
      - django_basic-django:/usr/src/app
      - django_basic-static:/usr/src/app/static
    env_file: ./django_basic/.env
    environment:
      - DEBUG='true'
      # The environment variable credentials that is needed 
      # in django settings for Postgres to work.
      - POSTGRES_HOST=postgres
      - POSTGRES_NAME
      - POSTGRES_USER
      - POSTGRES_PASSWORD=12345678
      - POSTGRES_PORT=5432
    depends_on:
      - postgres
    command: /usr/local/bin/gunicorn django_basic.wsgi:application -w 2 -b :8000
  

  postgres:
    restart: always
    image: postgres:15.2
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data/
    environment:
      # The environment variable credentials that is needed 
      # in django settings for Postgres to work.
      - POSTGRES_DB
      - POSTGRES_USER
      - POSTGRES_PASSWORD=12345678

volumes:
  django_basic-django:
  django_basic-static:
  pgdata:
